= Tracking Gradle Migration

Builds currently go to `builtByGradle` directory instead of `build` in order to make it easier to compare
Ant & Gradle builds.

== Overall TODO for each project

* ide-quick
* bundle-proxy
* Tests are disabled globally.

== Dist

.From dist/build.xml
[source,xml]
----
<target name="install-all"
    depends="setup-repo, install-compiler, install-js, copy-compiler-binaries, <!-- 1 --> <!-- 2 -->
             copy-samples, copy-templates, copy-contrib, copy-jvm-compiler-libraries,
             copy-licenses, install-runtime,
             add-module-descriptors, generate-buildid"
    description="Generates all binaries and copies them to the distribution folder">
</target>
----
<1> `setup-repo` handled `:runtime:setupRepo`
<2> `install-compiler` handled by `:common:publishInternal`.

== Commons

.From common/build.xml
[source,xml]
----
<target name="publish"
    depends="clean.repo,init.repo,dist,publish-internal" <!-- 1 --> <!-- 2 --> <!-- 3 -- >
    description="Publish both type checker and ceylon.language template module">
</target>
----
<1> `clean.repo` handled by `cleanRepo` which is a dependency of `clean`.
<2> `init.repo`, `publish-internal` handled by `publishInternal`.
<3> `dist` handled by Gradle dependency chain and included `assemble`, `sourceZip`, `sha1` and `jar`

== Cli

.TODO
* Should consider looking at `application` plugins to do a better job of bundling scripts. One task is
  specifically called `startScripts` to mimic a similar fucntionaing task in `application` plugin. This
  was done to deliberately break the build when the refactoring for `application` happens.

== Cmr

.TODO
* 17 tests are currently (disabled test task for moment)

== Cmr-aether

Compilation has been straight-forward.

.TODO
* Publishing
* Source Zip

== Cmr-webdav

Compilation has been straight-forward.

== Model

Compilation has been straight-forward.

== Langtools-classfile

This has been straight-forward to do. There are no `*.utf8properties` files in this project, but it has alerted to the
`native2ascii` Ant task that was used. The solution (which hopefully will work) is to hook into the lifecycle
`processResources` task, and fix the encodings on the fly using the Ant `EscapeUnicode` filter instead.

We also set `ceylonPublishModuleName` as this one uses two distinctly named property names from `common-build.properties`.

.TODO
* Do we need to set `-XDignore.symbol.file`  for `JavaCompile` options?

== buildSrc

A `buildSrc` folder has been added to help with some of the delicate and less common feastures of this build.

=== Checksum

A checksum task type has been added as `buildSrc/src/main.groovy/CheckSum.groovy`. This task can be used in conjuction
with any archiver tasks such as `Zip` & `Jar` to create checksums. By default a `sha1` task is added to each Java
project. This replaces the use of the `sha1sum` tasks in the Ant build.

=== Timestamp

A helper class has been added as `buildSrc/src/main.groovy/TimeStamp.groovy`. It sets a singular timestamp value
at the beginning of the build which can then be used in all builds via `TimeStamp.BUILD`. This replaces the use of
the `TStamp` ant task.

=== CeylonCommonBuildProperties

This is a plugin that is applied which loads up the properties from `common-build.properties` and places it on the
projet extension as a field called `cbp`.

It also provides a `requiresCBP` method that will fail the build if a specific property has not been found in
`common-build.properties`.

== gradle

A number of common functionality not suitable for buildSrc have been added as buildscript in the `gradle` folder

=== requires-common-build-properties.gradle

Provides a `requiresCBP` method that will fail the build is a specific property has not been found in
`common-build.properties`.

=== java-for-modules.gradle

Adds common `jar` and `publishInternal` configuration. It requires `ceylonModuleName` to be set before including it.
If `ceylonSourceLayout` is set to `false` before inclusion it will not set up `sourceSets` to use the Ant layout.

It assumes that `ceylonModuleName` is used in a consistent manner throughout a specific manner. This usually works,
but there some exceptions i.e. `classfile` and 'langtools.classfile`. For this case a subproject can manually set
`ceylonPublishModuleName` to the `ceylon.XXXX.dir` part.
