= Tracking Gradle Migration

Builds currently go to `builtByGradle` directory instead of `build` in order to make it easier to compare
Ant & Gradle builds.

== Overall TODO for each project

* ide-quick
* bundle-proxy

== Dist

.From dist/build.xml
[source,xml]
----
<target name="install-all"
    depends="setup-repo, install-compiler, install-js, copy-compiler-binaries, <!-- 1 --> <!-- 2 -->
             copy-samples, copy-templates, copy-contrib, copy-jvm-compiler-libraries,
             copy-licenses, install-runtime,
             add-module-descriptors, generate-buildid"
    description="Generates all binaries and copies them to the distribution folder">
</target>
----
<1> `setup-repo` handled `:runtime:setupRepo`
<2> `install-compiler` handled by `:common:publishInternal`.

== Commons

.From common/build.xml
[source,xml]
----
<target name="publish"
    depends="clean.repo,init.repo,dist,publish-internal" <!-- 1 --> <!-- 2 --> <!-- 3 -- >
    description="Publish both type checker and ceylon.language template module">
</target>
----
<1> `clean.repo` handled by `cleanRepo` which is a dependency of `clean`.
<2> `init.repo`, `publish-internal` handled by `publishInternal`.
<3> `dist` handled by Gradle dependency chain and included `assemble`, `sourceZip`, `sha1` and `jar`

== Cli

Awaiting `model`, `cmr`

== Cmr

.TODO
* Publishing
* Publish apiJar as well?
* Source Zip
* Need to check whether contents of `apiJar` should also be in `jar`.
* 17 tests are currently (disabled test task for moment)

== Cmr-aether

Compilation has been straight-forward.

.TODO
* Publishing
* Source Zip

== Cmr-webdav

Compilation has been straight-forward.

.TODO
* Publishing
* Source Zip

== Model

Compilation has been straight-forward.

.TODO
* Publishing
* Source Zip

== Langtools-classfile

This has been straight-forward to do. There are no `*.utf8properties` files in this project, but it has alerted to the
`native2ascii` Ant task that was used. The solution (which hopefully will work) is to hook into the lifecycle
`processResources` task, and fix the encodings on the fly using the Ant `EscapeUnicode` filter instead.

.TODO
* Publishing
* Source Zip

== buildSrc

A `buildSrc` folder has been added to help with some of the delicate and less common feastures of this build.

=== Checksum

A checksum task type has been added as `buildSrc/src/main.groovy/CheckSum.groovy`. This task can be used in conjuction
with any archiver tasks such as `Zip` & `Jar` to create checksums. By default a `sha1` task is added to each Java
project. This replaces the use of the `sha1sum` tasks in the Ant build.

=== Timestamp

A helper class has been added as `buildSrc/src/main.groovy/TimeStamp.groovy`. It sets a singular timestamp value
at the beginning of the build which can then be used in all builds via `TimeStamp.BUILD`. This replaces the use of
the `TStamp` ant task.