= Tracking Gradle Migration

Builds currently go to `builtByGradle` directory instead of `build` in order to make it easier to compare
Ant & Gradle builds.

== Overall TODO for each project

* ide-quick
* bundle-proxy
* Tests are disabled globally.

== Dist

.From dist/build.xml
[source,xml]
----
<target name="install-all"
    depends="setup-repo, install-compiler, install-js, copy-compiler-binaries, <!-- 1 --> <!-- 2 -->
             copy-samples, copy-templates, copy-contrib, copy-jvm-compiler-libraries,
             copy-licenses, install-runtime,
             add-module-descriptors, generate-buildid"
    description="Generates all binaries and copies them to the distribution folder">
</target>
----
<1> `setup-repo` handled `:runtime:setupRepo`
<2> `install-compiler` handled by `publishInternal` task in `common`, `cli`, `;angtools-classfile`,
  `model`, `cmr` ...

// typechecker etc.

.Currently waiting for
* `typechecker`
* `compiler-java`

== Commons

.From common/build.xml
[source,xml]
----
<target name="publish"
    depends="clean.repo,init.repo,dist,publish-internal" <!-- 1 --> <!-- 2 --> <!-- 3 -- >
    description="Publish both type checker and ceylon.language template module">
</target>
----
<1> `clean.repo` handled by `cleanRepo` which is a dependency of `clean`.
<2> `init.repo`, `publish-internal` handled by `publishInternal`.
<3> `dist` handled by Gradle dependency chain and included `assemble`, `sourceZip`, `sha1` and `jar`

== Cli

.TODO
* Should consider looking at `application` plugins to do a better job of bundling scripts. One task is
  specifically called `startScripts` to mimic a similar fucntionaing task in `application` plugin. This
  was done to deliberately break the build when the refactoring for `application` happens.

== Cmr

.TODO
* 17 tests are currently (disabled test task for moment)

== Cmr-aether

Standard Ceylon Java project.

.TODO
* Publishing
* Source Zip

== Cmr-webdav

Standard Ceylon Java project.

== Model

Standard Ceylon Java project.

== Langtools-classfile

This has been straight-forward to do. There are no `*.utf8properties` files in this project, but it has alerted to the
`native2ascii` Ant task that was used. The solution (which hopefully will work) is to hook into the lifecycle
`processResources` task, and fix the encodings on the fly using the Ant `EscapeUnicode` filter instead.

We also set `ceylonPublishModuleName` as this one uses two distinctly named property names from `common-build.properties`.

.TODO
* Do we need to set `-XDignore.symbol.file`  for `JavaCompile` options?

== Typechecker

Usage of Gradle's builtin `antlr` plugin did not work due to a showstopper bug. Sticking wil the old `build.xml` is not
ideal as automatic management of artifacts for project dependencies will be lost. Created `CeylonAntlr` plugin to solve
the problem.

The equivalent of the Ant `treegen` task has been solved by creating a sourceset called `treegen`. This automatically
 creates a `compileTreegenJava` tasks which is then made dependent on `generateGrammarSource`.

The `tree` used a class called `Generate` to create further Java files for later compilation. It was discovered that
the `Generate` class has a hardcoded path that starts with `gensrc`.
For this reason the generated source directory is configured in the subproject to be `gensrc`, but located under the
build directory. The Gradle `tree` task used the build directory has working directory and references back to the
project directory to find the `Ceylon.nodes` file. it also manually sets an output directory property so that Gradle
can have an idea when it is up to date.

Finally `compileJava` has to depend on `tree`, whereafter all of the tasks supplied via `java-for-modules.gradle`,
starts to work.

.TODO
* The Ant `antlr.tree` deleted tokens at the end. SHould we still do that?

== Compiler-java

.TODO
* Waiting for `typechecker` to be completed.

== buildSrc

A `buildSrc` folder has been added to help with some of the delicate and less common feastures of this build.

=== Checksum

A checksum task type has been added as `buildSrc/src/main.groovy/CheckSum.groovy`. This task can be used in conjuction
with any archiver tasks such as `Zip` & `Jar` to create checksums. By default a `sha1` task is added to each Java
project. This replaces the use of the `sha1sum` tasks in the Ant build.

=== Timestamp

A helper class has been added as `buildSrc/src/main.groovy/TimeStamp.groovy`. It sets a singular timestamp value
at the beginning of the build which can then be used in all builds via `TimeStamp.BUILD`. This replaces the use of
the `TStamp` ant task.

=== CeylonCommonBuildProperties

This is a plugin that is applied which loads up the properties from `common-build.properties` and places it on the
projet extension as a field called `cbp`.

It also provides a `requiresCBP` method that will fail the build if a specific property has not been found in
`common-build.properties`.

=== CeylonAntlr

A local plugin that mimics a number of conventions of the builtin Gradle `antlr` plugin, but is stripped down in
functionality and covers just enough to work within the Ceylon build environment.

== gradle

A number of common functionality not suitable for buildSrc have been added as buildscript in the `gradle` folder

=== java-for-modules.gradle

Adds common `jar` and `publishInternal` configuration. It requires `ceylonModuleName` to be set before including it.
If `ceylonSourceLayout` is set to `false` before inclusion it will not set up `sourceSets` to use the Ant layout.

It assumes that `ceylonModuleName` is used in a consistent manner throughout a specific manner. This usually works,
but there some exceptions i.e. `classfile` and 'langtools.classfile`. For this case a subproject can manually set
`ceylonPublishModuleName` to the `ceylon.XXXX.dir` part.
