package com.redhat.ceylon.compiler.java.language;

import ceylon.language.Callable;

/**
 * Stub implementation for {@link Callable}, so the anonymous inner classes 
 * generated by the compiler only need to define a single method.
 *
 * @param <Return>
 */
public class AbstractCallable<Return> implements Callable<Return> {
    public Return call() {
        throw new UnsupportedOperationException();
    }
    
    public Return call(java.lang.Object arg0) {
        throw new UnsupportedOperationException();
    }
    
    public Return call(java.lang.Object arg0, java.lang.Object arg1) {
        throw new UnsupportedOperationException();
    }
    
    public Return call(java.lang.Object arg0, java.lang.Object arg1, java.lang.Object arg2) {
        throw new UnsupportedOperationException();
    }
    
    public Return call(java.lang.Object... args) {
        throw new UnsupportedOperationException();
    }
}