package com.redhat.ceylon.compiler.java.language;

import ceylon.language.impl.BaseIterator;

import com.redhat.ceylon.compiler.java.metadata.Ignore;
import com.redhat.ceylon.compiler.java.runtime.model.TypeDescriptor;

/** 
 * A non-user-visible class that helps create iterators in 
 * generated bytecode.
 * 
 * @author Enrique Zamudio
 */
public abstract class AbstractIterator<Element> 
extends BaseIterator<Element> {
    
    public AbstractIterator(@Ignore TypeDescriptor $reifiedElement) {
    	super($reifiedElement);
    }
    
}
