require('default/misc').testit();
require('default/invocations').invocations();
require('default/language').test();
require('default/nesting').test();
require('default/members').test();
require('default/types').test();
require('default/operators').test();
require('default/flow').test();
require('default/functions').test();
