#!/bin/sh
ceylon=../../ceylon/dist/dist/bin/ceylon
$ceylon compile-js com.redhat.ceylon.compiler.js.typescript &&
$ceylon run-js com.redhat.ceylon.compiler.js.typescript/1.0.0 tsmodule 1 src/test/ceylon/typescript/tsmodule.ts &&
false &&
$ceylon compile-js --src src/test/ceylon typescript &&
$ceylon run-js typescript
